name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install protobuf
      run: |
            apk add --update make git
            git describe --tags
            git symbolic-ref --short HEAD
            pwd
            make install-prototool
            prototool version
    
    - name: Build
      run: cargo build --verbose
      working-directory: builder

    # - name: Test
    #   run: cargo test --verbose
  
  # java:
  #   runs-on: ubuntu-latest
